#Step 1 - Install software git, ssh,docker, ansible, packer, terraform, docker-machine
- name: AIPC Day 2 Workshop
  hosts: all
  tasks:
  - name: Task 2a - Install patches
    apt:
      update_cache: yes
      name: "*"
      state: latest
  #- name: Task 2b - Reboot server
  - name: Reboot the machine with all defaults using Ansible
    reboot:
  - name: Task 3a - Install packages (GIT, SSH,Ansible, packer, nginx)
    apt:
      name: "{{ item }}"
      update_cache: yes
      state: present
    loop:
    - git
    - ssh
    - ansible
    - packer
    - nginx
  - name: Install unzip
    apt: pkg=unzip=6.0* state=present  
  -name: Install pip on the servers
      yum:
        name: python-pip
        state: latest
        update_cache: true
      become: true

    - name: Install pip3 on the servers
      yum:
        name: python3-pip
        state: latest        
      become: true

    - name: Ensure ansible is installed on servers
      pip:
        name: ansible

    - name: Executing ansible-pull on servers
      command: ansible-pull -U https://gitlab.com/hemanth22/ansible-pull-terraform.git

  - name:  Task 6 - Install ngingx Step X - Enable nginx
    systemd:
      name: nginx 
      enabled: yes
      state: started