#Step 1 - Install software git, ssh,docker, ansible, packer, terraform, docker-machine
- name: AIPC Day 2 Workshop
  hosts: all
  tasks:
  - name: Install patches
    apt:
      update_cache: yes
      name: "*"
      state: latest
  #- name: Task 2b - Reboot server
  - name: Reboot the machine with all defaults using Ansible
    reboot:
  - name: Task 3a - Install packages (GIT, SSH,Ansible, packer, nginx)
    apt:
      name: "{{ item }}"
      update_cache: yes
      state: present
    loop:
    - git
    - ssh
    - ansible
    - packer
    - nginx
  - name: Install unzip
    apt: pkg=unzip=6.0* state=present  
  -name: Install pip on the servers
      yum:
        name: python-pip
        state: latest
        update_cache: true
      become: true

    - name: Install pip3 on the servers
      yum:
        name: python3-pip
        state: latest        
      become: true

    - name: Ensure ansible is installed on servers
      pip:
        name: ansible

    - name: Executing ansible-pull on servers
      command: ansible-pull -U https://gitlab.com/hemanth22/ansible-pull-terraform.git
 - name: Install terraform
    unarchive:
      src: https://releases.hashicorp.com/terraform/1.1.0/terraform_1.1.0_linux_amd64.zip
      dest: /usr/local/bin
      remote_src: true
  - name: Install packer
    unarchive:
      src: https://releases.hashicorp.com/packer/1.7.8/packer_1.7.8_linux_amd64.zip
      dest: /usr/local/bin
      remote_src: true

  - name: Install docker-machine
    get_url:
      url: https://gitlab-docker-machine-downloads.s3.amazonaws.com/main/docker-machine-Linux-x86_64
      dest: /usr/local/bin/docker-machine
      mode: "a+x"

  - name: Create user fred
    user: 
      name: fred
      shell: /bin/bash
      groups: docker,sudo
      append: yes
      state: present
  - name: add ssh keys to fred
    authorized_key:
      user: fred
      state: present
      key: "{{ lookup('file', public_key_file) }}"
  - name: add instructor's SSH key
    authorized_key:
      user: fred
      state: present
      key: https://drive.google.com/u/0/uc?id=17pBBYJhRkyrfVhLu44e23CA2PbeXPuMg&export=download

  - name: List all files in /var/www/html
    find:
      paths: /var/www/html
      recurse: yes 
    register: html_files 
  - name: echo html_files
    debug:
      msg: ">>> {{ html_files }}"
  - name: delete files from /var/www/html
    file:
      name: "{{ item.path }}"
      state: absent
    loop: "{{ html_files.files }}"
  - name: Copy HTML files over to server
    copy:
      src: ./nginx-assets/ 
      dest: /var/www/html/

  - name:   Install ngingx Step X - Enable nginx
    systemd:
      name: nginx 
      enabled: yes
      state: started